# Change these first
owner: neonlabsorg # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: NeonEVM website
    url: https://neonevm.org
    __dangerous__body_down_if_text_missing: NeonEVM
  - name: Neonpass service
    url: https://neonpass.live
    __dangerous__body_down_if_text_missing: NeonPass
  - name: Neonscan service
    url: https://neonscan.org
    __dangerous__body_down_if_text_missing: '<div id="root"></div>'
  - name: Neonscan API
    url: https://api.neonscan.org/block/lastest?offset=0&limit=1
    __dangerous__body_down_if_text_missing: '"success":true'  
    icon: https://neonscan.org/favicon.png
  - name: Mainnet proxy on P2P
    url: https://neon-proxy-mainnet.solana.p2p.org
    method: POST
    headers:
      - "Content-Type: application/json"
    body: '{ "jsonrpc": "2.0", "method": "web3_clientVersion", "params": [], "id": 1 }'
    icon: https://cdn.prod.website-files.com/661ce38fc2cbb4e39a655100/661e5a04c53f2dcc93c360b0_32x32.svg
  - name: Mainnet proxy on Everstake
    url: https://neon-mainnet.everstake.one
    method: POST
    headers:
      - "Content-Type: application/json"
    body: '{ "jsonrpc": "2.0", "method": "web3_clientVersion", "params": [], "id": 1 }'
    icon: https://avatars.githubusercontent.com/u/49940420
  - name: Devnet proxy
    url: https://devnet.neonevm.org/solana
    method: POST
    headers:
      - "Content-Type: application/json"
    body: '{ "jsonrpc": "2.0", "method": "web3_clientVersion", "params": [], "id": 1 }'
    icon: https://icons.duckduckgo.com/ip3/neonevm.org.ico
assignees:
  - DevOps
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.neonevm.org
  # baseUrl: /
  logoUrl: https://neonevm.org/img/logo.svg
  name: NeonEVM Status Page
  introMessage: Status page for the NeonEVM services
  navbar:
    - title: Status
      href: /
    - title: Site
      href: https://neonevm.org/
    - title: GitHub
      href: https://github.com/neonevm

i18n:
  footer: Neon Foundation, 2025
